name: wilcoerp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependency_overrides:
  platform: ^3.1.0
  
dependencies:
  flutter:
    sdk: flutter
  provider: any
  flutter_localizations:
    sdk: flutter
  progress_indicators: 1.0.0
  flutter_page_transition: 0.1.0
  simple_animations: 1.3.3
  # font_awesome_flutter: 8.8.1
  font_awesome_flutter: 9.0.0
  google_maps_flutter: 2.1.3 #no support web
  http: ^0.13.1
  intl: ^0.17.0
  dio: ^4.0.0
  location_permissions: 3.0.0
  geolocator: 8.2.0
  simple_barcode_scanner: ^0.0.8
  carousel_slider: 4.0.0
  photo_view: 0.13.0
  image_picker: 0.8.4+2
  date_time_picker: ^2.1.0
  url_launcher: 6.1.1
  shimmer_animation: 2.1.0+1
  snack: 2.0.0
  flutter_rounded_date_picker: ^3.0.4
  flutter_datetime_picker: 1.5.1
  shared_preferences: 2.0.8

  record_mp3: any
  #audio_recorder: any
  path_provider: any
  permission_handler: any
  voice_message_package: any




  cupertino_icons: ^1.0.2

flutter_icons:
  image_path_ios: 'assets/images/app_icons/icon_main.png'
  image_path_android: 'assets/images/app_icons/icon_main.png'
  adaptive_icon_background: 'assets/images/app_icons/icon_background.png'
  adaptive_icon_foreground: 'assets/images/app_icons/icon_foreground.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_name: ^0.0.1 #run: flutter pub run flutter_launcher_name:main
  #flutter_launcher_icons: any #flutter pub run flutter_launcher_icons:main
  change_app_package_name: ^0.1.2

  flutter_lints: ^2.0.0

flutter_launcher_name:
  name: "Wilco ERP" #run: flutter pub run flutter_launcher_name:main

flutter:
  uses-material-design: true
  assets:
        - assets/
        - assets/images/
        - assets/images/app_icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf



